language: node_js

node_js:
  - "8"

branches:
 only:
   - master

before_install:
  # - npm install -g npm@3
  - npm -v
  - node -v

install:
  - npm install

# after_install:
#   - ls -la node_modules/ 

script:
  - npm run lint
  - npm run test:coveralls